name: Sigee Watcher

on:
  schedule:
    # Run every 1 minutes
    - cron: "* * * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  run-watcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Cache processed posts
        uses: actions/cache@v4
        with:
          path: .cache
          key: ${{ runner.os }}-processed-posts-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-processed-posts-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Run watcher
        run: pnpm start
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # GITHUB_OWNER: ${{ secrets.GITHUB_OWNER }}
          # GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
          # DISCUSSION_REPO: ${{ secrets.DISCUSSION_REPO }}
          # DISCUSSION_REPO_ID: ${{ secrets.DISCUSSION_REPO_ID }}
          # DISCUSSION_CATEGORY_ID: ${{ secrets.DISCUSSION_CATEGORY_ID }}
